EmployeeERP/Controllers/RequestController.cs
using AutoMapper;
using EmployeeERP.Models.DbEntities;
using EmployeeERP.Models.DTO;
using EmployeeERP.Models.ViewModel;
using EmployeeERP.Services.Repository;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeERP.Controllers
{
    public class RequestController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IGenericRepository<Employee> _employeeRepository;
        private readonly IGenericRepository<TimeOffRequest> _timeOffRepository;


        public RequestController(IMapper mapper, IGenericRepository<Employee> employeeRepository, IGenericRepository<TimeOffRequest> timeOffRepository )
        {
            _employeeRepository = employeeRepository;
            _timeOffRepository = timeOffRepository;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Employees"] = _mapper.Map<ICollection<Employee>, ICollection<EmployeeDto>>(await _employeeRepository.GetAllAsync());
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateTimeOffRequest(CreateRequestViewModel timeOffRequest) 
        {

            ViewData["Employees"] = _mapper.Map<ICollection<Employee>, ICollection<EmployeeDto>>(await _employeeRepository.GetAllAsync());
            if (ModelState.IsValid)
            {
                var request = new TimeOffRequest
                {
                    TimeOffStart = timeOffRequest.TimeOffStart,
                    TimeOffEnd = timeOffRequest.TimeOffEnd,
                    Description = timeOffRequest.Description,
                    EmployeeId = timeOffRequest.EmployeeId,
                };
                var success = await _timeOffRepository.AddAsync(request);
                if (!success)
                {
                    ModelState.AddModelError(string.Empty, "Hiba történt a feltöltés során.");
                    return View("Index", timeOffRequest);
                }
                return RedirectToAction("Index");
            }

            // Ha az űrlap adatok nem érvényesek, akkor maradj a jelenlegi nézeten és jelenítsd meg a hibákat.
            return View("Index", timeOffRequest);
        }
    }
}

EmployeeERP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeERP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeERP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeERP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Alkalmazottak</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Új igény</a>
                        </li>
                        <li class="nav-item ms-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Bejelentkezés</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EmployeeERP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>